title: Oomph Grey Matter
description: A wireframe system for quick HTML/SASS prototypes
  
markdown: redcarpet
highlighter: pygments

baseurl: '/oomph-grey-matter/'
port: 4040
url: //jhogue.dev.oomphcloud.com
twitter_handle: oomphinc


# Define some defaults
defaults:
  -
    values:
      layout: "page"
      author: "Oomph, Inc."


# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['.git', '.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'feed.xml']


#Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass
  

# Plugins and extras
plugins:
- jekyll-autoprefixer
