source "https://rubygems.org"

gem "jekyll", ">=3.0.0"
gem "jekyll-watch", ">=1.5"
gem 'jekyll-autoprefixer', ">=1.0.0"
gem "jekyll-assets", ">=3.0.0"
gem "liquid", ">=4.0.0"
gem "pygments.rb", ">=1.2.1"
gem "redcarpet", ">=3.1"
gem "rake", ">=12.0"
gem "sass",">=3.5.3"
gem "sass-globbing"
gem "uglifier"
