source "https://rubygems.org"

gem "jekyll", ">=3.8.5"
gem "jekyll-watch", ">=2.0.0"
gem "jekyll-sass-converter", ">=1.3.0"
gem 'jekyll-autoprefixer', ">=1.0.0"
gem "jekyll-assets", ">=3.0.0"
gem "liquid", ">=4.0.0"
gem "pygments.rb", ">=1.2.1"
gem "redcarpet", ">=3.1"
gem "rake", ">=10.0.0"
gem "sass",">=3.7.0"
gem "sass-globbing",">=1.1.0"
gem "uglifier",">=4.1.0"
